### ISSUE TITLE
Go struct storage and binding

### ISSUE THREAD

**Issue by ghost** [go-humble/locstor#1]
It seems like it only stores primitive data types.
Can it store struts and retrieve struts serialised as json ?

**Comment by albrow** [comment]
The native localStorage API only supports string items, so I mimicked that behavior. `SetItem`, `GetItem`, etc. only work with strings.

If you want to store other data structures, you can use a `DataStore`object, which is an abstraction built on top of the localStorage API. Check out the [Using a DataStore](https://github.com/go-humble/locstor#using-a-datastore) section of the README and the [documentation on the `DataStore` type](https://godoc.org/github.com/go-humble/locstor#DataStore). Let me know if anything is not clear in the documentation!

**Comment by ghost** [comment]
Thank. Makes sense.
